=== ilabutin/spbdotnet-2017-msbuild/MeetupInfo-2/MeetupInfo/MeetupInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="MeetupInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Date" type="xs:dateTime"/>
				<xs:element name="Speakers">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="SpeakerInfo">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Name" type="xs:string"/>
										<xs:element name="Mail" type="xs:string"/>
										<xs:element name="Approved" type="xs:boolean"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ilabutin/spbdotnet-2017-msbuild/MeetupExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<MeetupInfo xsi:noNamespaceSchemaLocation="MeetupInfo.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Date>2017-04-13T16:00:00Z</Date>
	<Speakers>
		<SpeakerInfo>
			<Name>Igor Labutin</Name>
			<Mail>ilabutin@gmail.com</Mail>
			<Approved>true</Approved>
		</SpeakerInfo>
		<SpeakerInfo>
			<Name>Jon Skeet</Name>
			<Mail>skeet@pobox.com</Mail>
			<Approved>false</Approved>
		</SpeakerInfo>
	</Speakers>
</MeetupInfo>
